version: '2.1'

services: 
  web:
    container_name: insource-node
    restart: always
    build: .
    ports:
      - '80:3000'
    networks:
      - webnet
    environment:
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: mysql-db
    image: mysql:5.7
    ports:
      - '3306:3306'
    networks:
      - webnet
    environment:
      - MYSQL_DATABASE=insource
      - MYSQL_ROOT_PASSWORD=anri1991
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
networks: 
  webnet: