version: '3.7'

services: 
  web:
    container_name: insource-node
    restart: always
    build: .
    ports:
      - '80:3000'
    networks:
      - webnet
    environment:
      DB_HOST: db
  db:
    container_name: mysql-db
    image: mysql:5.7
    ports:
      - '3306:3306'
    networks:
      - webnet
    environment:
      - MYSQL_ROOT_PASSWORD=anri1991
      - MYSQL_DATABASE=insource
      - MYSQL_USER=anrito
      - MYSQL_PASSWORD=anri1991
networks: 
  webnet: